global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

#  - job_name: 'cpu'
#    static_configs:
#      - targets: ['localhost:9100']
#    metrics_path: /metrics
#    params:
#      module: [cpu]

#  - job_name: 'memory'
#    static_configs:
#      - targets: ['localhost:9100']
#    metrics_path: /metrics
#    params:
#      module: [meminfo]
